spring.application.name=order-service

server.port=8081
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/gelatinas_orders}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.flyway.enabled=true
gelatinas.transfer.default-price=80.00

spring.security.user.name=${ADMIN_USERNAME}
spring.security.user.password=${ADMIN_PASSWORD}
spring.security.user.roles=ADMIN

ADMIN_USERNAME=admin
ADMIN_PASSWORD=Kalhel10#
